version: '2'
services:
  playground-cassandra:
    image: cassandra:3.11.4
    # volumes:
    #     - ~/volumes/jhipster/Playground/cassandra/:/var/lib/cassandra/data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  playground-cassandra-node:
    image: cassandra:3.11.4
    environment:
      - CASSANDRA_SEEDS=playground-cassandra
  playground-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: playground-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
